version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "4444:3306"
    volumes:
      - my_db:/var/lib/mysql
      - ./db_scripts:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db
  
  nginx:
    image: nginx:alpine
    container_name: nginx-images
    ports:
      - "8081:80"
    volumes:
      - ./images:/usr/share/nginx/html/images
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped




volumes:
  my_db:
